### ISSUE TITLE
Toggle panels in light mode is doesn't work correctly

### ISSUE THREAD

**Issue by DannyvdSluijs** [infi-nl/the-infi-way#88]
When viewing the Infi way in light mode the toggle buttons don't work correctly due to some reasons:
- The individual toggle for each pane has a poor contrast to the background (See screenshot).
- When playing around with a combination of the toggle all and a toggle individual panel the icon can result in the toggle all icon to be missing (see screenshot).

![Screenshot 2023-08-31 at 09 36 54](https://github.com/infi-nl/the-infi-way/assets/618940/33919f5a-99e2-47af-af86-2bae7e12c119)

**Comment by jeroenheijmans** [comment]
This has been effectively fixed by a recent PR (#94) the design is now a bit more accessible and clear in general:

![image](https://github.com/infi-nl/the-infi-way/assets/1590536/20176680-3451-427a-b639-6179f1ffc51a)

I'll take the liberty of closing this bug, ping me if you feel it should be reopened.
